# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  default:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm i
    - run: npm run build --if-present
    - run: npm test


  ol-versions:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ol-version: [ '6.10', '6.11', '6.12', '6.13', '6.14', '6.14.1' ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm i
    - run: npm i ol@${{ matrix.ol-version }}
    - run: npm run build --if-present
    - run: npm test


  react-versions:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        react-version: [ '16.8', '16.14', '17.0.2' ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm i react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }} react-test-renderer@${{ matrix.react-version }} react-bootstrap@1.6.4 @testing-library/react@11
    - run: npm i
    - run: tsc
    - run: npm test
    - run: npm run build:examples


  react-18:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm i react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }} react-test-renderer@${{ matrix.react-version }} react-bootstrap@1.6.4
    - run: npm i
    - run: tsc
    - run: npm test
    - run: npm run build:examples


  codecov:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm i
    - run: npm run test
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - run: npm run codecov
